name: app_transcricao
description: Aplicativo de transcriÃ§Ã£o com ONNX
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  record: ^6.1.2          # versÃ£o estÃ¡vel antes das grandes mudanÃ§as
  record_platform_interface: ^1.4.0
  path_provider: ^2.1.2
  ffi: ^2.1.1
  wav: ^1.0.0   # ðŸ‘ˆ adicionado aqui
  audio_session: ^0.2.2
  fftea: ^1.3.1         # FFT para espectrograma
  onnxruntime: ^1.4.1    
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/citrinet_encoder_decoder.onnx
    - assets/models/labels.json
