name: app_transcricao
description: Aplicativo de transcrição com ONNX
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  record: ^6.1.2
  record_platform_interface: ^1.4.0
  path_provider: ^2.1.2
  ffi: ^2.1.1
  wav: ^1.0.0
  audio_session: ^0.2.2
  fftea: ^1.3.1
  onnxruntime: ^1.4.1
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1   

flutter_launcher_icons:            
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/models/citrinet_encoder_decoder.onnx
    - assets/models/labels.json
